name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-windows:
      env:
        IN_PIPELINE: true
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          type: [windows-x64, windows-x86]
          include:
            - type: windows-x64
              os: windows-latest
              target: x86_64-pc-windows-msvc

      steps:
        - uses: actions/checkout@v4
        - name: Cache cargo & target directories
          uses: Swatinem/rust-cache@v2
        - name: Build binary
          uses: houseabsolute/actions-rust-cross@v0
          with:
            command: build
            target:  ${{ matrix.target }}
            args: "--locked --release"
            strip: true
            toolchain: stable
