name: Rust release

on:
  push:
    tags:
      - 'v*'  # Triggers only when pushing version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create a GitHub Release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Windows x86_64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: route2wsl-x86_64.exe
          path: dist/

      - name: Download Windows x86 Artifact
        uses: actions/download-artifact@v4
        with:
          name: route2wsl-x86.exe
          path: dist/

      - name: List downloaded files
        run: ls -R dist

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*.exe