name: Rust Release

on:
  push:
    tags:
      - 'v*'  # Triggers release job on version tag push

jobs:
  build-windows:
    name: Build (Windows Targets)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        type: [windows-x64, windows-x86]
        include:
          - type: windows-x64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            name: route2wsl-x86_64.exe
            path: target\x86_64-pc-windows-msvc\release\route2wsl.exe
          - type: windows-x86
            os: windows-latest
            target: i686-pc-windows-msvc
            name: route2wsl-x86.exe
            path: target\i686-pc-windows-msvc\release\route2wsl.exe

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target
        uses: Swatinem/rust-cache@v2
      - name: Build Rust binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}

  release:
    name: Release
    needs: [build-windows]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Windows x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: route2wsl-x86_64.exe
          path: dist/

      - name: Download Windows x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: route2wsl-x86.exe
          path: dist/

      - name: List release files
        run: ls -R dist

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*.exe
